import json
import inspect
from fastapi import FastAPI
from fastapi.routing import APIRoute
from ai_engine import llm_generate_summary
from typing import Any, Dict, List


# Extract FastAPI routes

def extract_routes(app: FastAPI) -> List[Dict[str, Any]]:
    routes = []
    for route in app.routes:
        if isinstance(route, APIRoute):
            routes.append({
                "path": route.path,
                "methods": list(route.methods),
                "name": route.name,
                "endpoint": route.endpoint.__name__,
                "doc": inspect.getdoc(route.endpoint) or "",
            })
    return routes



# Generate Markdown documentation with LLAMA


def generate_markdown(routes: List[Dict[str, Any]]) -> str:
    lines = ["# API Documentation (Generated by AI)", ""]

    for r in routes:
        summary = llm_generate_summary(r["doc"] or r["name"])

        lines.append(f"## {r['name']}")
        lines.append(f"**AI Summary:** {summary}")
        lines.append(f"**Path:** `{r['path']}`")
        lines.append(f"**Methods:** {', '.join(r['methods'])}")
        lines.append(f"**Original Docstring:** {r['doc']}")
        lines.append("")
    return "\n".join(lines)



# Simple OpenAPI generator (basic version)
def generate_openapi(routes: List[Dict[str, Any]]):
    openapi = {"openapi": "3.1.0", "paths": {}}

    for r in routes:
        entry = {}
        for m in r["methods"]:
            entry[m.lower()] = {
                "summary": r["doc"] or r["name"],
                "operationId": r["endpoint"]
            }
        openapi["paths"][r["path"]] = entry

    return openapi


# AI-generated test case suggestions
def ai_generate_tests(route):
    prompt = (
        f"Generate 3 useful test cases for the following API endpoint:\n{route}"
    )
    return llm_generate_summary(prompt)


def generate_testcases(routes):
    tests = []
    for r in routes:
        tests.append({
            "endpoint": r["path"],
            "methods": r["methods"],
            "ai_suggested_tests": ai_generate_tests(r)
        })
    return {"tests": tests}
